MINIZ_VERSION = 3.0.2
MINIZ_SITE =  $(call github,richgel999,miniz,$(MINIZ_VERSION))
MINIZ_LICENSE = MIT
MINIZ_CONF_OPTIONS = -DBUILD_SHARED_LIBS=ON
MINIZ_INSTALL_STAGING = YES


$(eval $(cmake-package))