#!/bin/sh

case "$1" in
  start)
    printf "start lcd: "
    if [ -e /boot/bpp16 ]
    then
        modprobe soph_fb.ko
    else
        modprobe soph_fb.ko
    fi
    /usr/bin/fbdaemon
    echo "OK"
    ;;
  stop)
    printf "stop lcd: "
    killall fbdaemon
    echo "OK"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
